apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf
  template:
    metadata:
      name: chronograf
      labels:
        app: chronograf
    spec:
      containers:
      - name: chronograf
        image: chronograf:services
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8888
        env:
        - name: INFLUXDB_URL
          value: "http://influxdb:8086"
        - name: INFLUXDB_USERNAME
          value: "admin"
        - name: INFLUXDB_PASSWORD
          value: "1234"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: chronograf
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 8888
  selector:
    app: chronograf
  type: LoadBalancer
