apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      name: ftp
      labels:
        app: ftp
    spec:
      containers:
      - name: ftp
        image: ftp:services
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 21
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftp
spec:
  ports:
  - name: http
    protocol: TCP
    port: 21
    targetPort: 21
  selector:
    app: ftp
  type: LoadBalancer
