apiVersion: v1
kind: ConfigMap
metadata:
  name: ftp-config
data:
  vsftpd.conf: |
    pasv_address=192.168.99.101
    pasv_enable=Yes
    pasv_min_port=30000
    pasv_max_port=30100
    port_enable=YES
    anonymous_enable=YES
    local_enable=YES
    write_enable=YES
    ftpd_banner=Welcome to Caio FTP server.
    chroot_local_user=NO
    allow_writeable_chroot=YES
    listen=YES
    seccomp_sandbox=NO
    user_sub_token=$USER
    local_root=/home/$USER/ftp
    rsa_cert_file=/etc/ssl/server.crt
    rsa_private_key_file=/etc/ssl/server.key
    ssl_enable=YES
    allow_anon_ssl=YES
    force_local_data_ssl=YES
    force_local_logins_ssl=YES
    ssl_tlsv1=YES
    ssl_sslv2=NO
    ssl_sslv3=NO
    require_ssl_reuse=NO
    ssl_ciphers=HIGH
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      name: ftp
      labels:
        app: ftp
    spec:
      containers:
      - name: ftp
        image: ftp:services
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 21
        volumeMounts:
        - name: ftp-config
          mountPath: /etc/vsftpd/
      volumes:
        - name: ftp-config
          configMap:
            name: ftp-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftp
spec:
  ports:
  - name: http
    protocol: TCP
    port: 21
    targetPort: 21
  selector:
    app: ftp
  type: LoadBalancer
