{
 "title": "csouza-f",
 "description": "ft_services",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ns", "label": "Namespace", "query": "default" },
   {
    "name": "name",
    "label": "Container Name",
    "query": "nginx,ftp,wordpress,phpmyadmin,grafana"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Millicores - $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage_nanocores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$ns$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Usage - $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    },
    {
     "alias": "RSS - $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_rss_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    },
    {
     "alias": "Page Faults - $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_page_faults" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    },
    {
     "alias": "Major Page Faults - $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_major_page_faults" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "RX - $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_network",
     "query": "SELECT mean(\"value\") FROM \"network/rx_rate\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$ns$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^$name.*/" }
     ]
    },
    {
     "alias": "TX - $tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_network",
     "query": "SELECT mean(\"value\") FROM \"network/tx_rate\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Filesystem",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Used - $tag_volume_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "volume_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_volume",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    },
    {
     "alias": "Available - $tag_volume_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "volume_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_volume",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "available_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    }
   ]
  }
 ]
}