apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssl
type: Opaque
data:
  server.key:
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA2aS8eimv/AhGjNfqck3uYHVTcwWw8pg9Q4rwJNjUJQbvPq7P
    MNC2tcgrqVvUXGW4Eco9xvTx/ylLilQhCeyO/epo2Mw3RFOtsrt863S5GbQbA6tR
    HIM1Mf9Kz4FcuT9ON8sq6NVU6dh3G4Oq8O3rhNb5Of1UUZLqpQfi9yYLkZyuUvne
    tNpFZkgT0DQh2//bCsdIfKXzvaan8BKaYuokOj20aH4m3WxJpQRajLBPXc2PvDeM
    n+z9PDXTeY2ukgGBEocyT1xU/qP5YYtAts9vfpDf+yh1fYnCrjzTYb5fPz+O7blp
    uMbf19cPfjoKuhdQwFEvvOeyJbC2PZ8b5WuwswIDAQABAoIBAACblCcnLKWghEnq
    ZG4zR4Ifcb81edwDjtA8eBUyQc1kqpBbPprdSlVRnMWZSwuDATOTg/6lOnPC8sIN
    IBZ+AZw15lsMnu7i6O5B1cR2i/nFZfnppY1V1HUySEwyCUc/JQHE4HbL+bO5dgOu
    p3CKyYiSbRm7Wlvr9BnH3ttf0NJ0Qzptu2fPYj3I+eyMbdlzqnSwMF01ftT8D+WP
    gAsggGIRWSPcmkyg9NshMhxGJSdSgI7e8bmLY5yN7DWePHc7/OGPgvusjvZ6pKWU
    WS3mY54hZlbxzqqz6yPoHVzyLL37hC8vq8PWgj9zk1mOONsec3F4P75LCYYOWdpC
    NMk6y5kCgYEA+JzF6UqHinkTVFdu+mk8HxCu1K7KpmaCWNg5s5CN4JQ41dwDf79Z
    y706juFe1y6MaKnizavPJbovZSGehX+cuV3GgL7gz/Nw/omuPrw9Zp+G/+iDEdzh
    toNsatBvnc9I3Bvt6GdukyKgRfM8p7uRnQVBqUrfxQ21Hv0pMQH2Rq0CgYEA4Bxg
    9KgrfSN1gS+IccHID2qBTBP/nc4ydspaJ7FsVm/WaiVR2/O/RzpAXeW2/dNofUgv
    ioKlUUq4bDAkM5raIHgM33fxiTAfOBVsCKA+xmVPKbu1UiCJfbklXUqcIb3w3poK
    hjOVu0byhNAilOC3RroXnt4NxzFWpcl4pyGYoN8CgYEAtYVqL8MeIenzRhKs0iOC
    JUB+FoYlKsgQBiSiRMyX+tDeiq+g0mZ5fvwERIyjPcQb+tOH6Rm4HtjJgDLC1sBt
    Qx8IL7qu1MbvyrnmQqIYxtRVsoYnJSS8nRFqWLclt/jAPw4ZcCYNI1sV4N0PfXzD
    ff13is9DgVJX22+G4uSG1+UCgYBiphtHln8OJn2iz/mPmW0m3AruIh9yp0EvaQMm
    VcMKiVAoiSTvXOvlvo52xpc2Q8jK3OuQXNHIZsunU8mbrZ42jKGd/H4llTkoxsU3
    RtJbIl0mUaoO7KOY49a+qgjwEVvloIjhafOO7Dv0mmmefwwt5dxf4f7On7k0YOrr
    Jq64oQKBgG74Mw4sjpNU3JIcLpJeYwj8xg4RBNw56DyVi6gXM36ncaNC4aFkkQbP
    gKsUS+MIagnzNbRod1q3L/lfKKg3016SDX9TGVYW+8RO5GbQsSO1iZgir+9pzVNg
    2aPV8jxy7uzZjspVaRjt46Q7y1lzJDEf5Bl+hsaIQvNys4ZlJxXI
    -----END RSA PRIVATE KEY-----
  server.crt:
    -----BEGIN CERTIFICATE-----
    MIIDhTCCAm0CFBqB1mQK0TTOkXdMhglOPb3b4ILTMA0GCSqGSIb3DQEBCwUAMH8x
    CzAJBgNVBAYTAkJSMRIwEAYDVQQIDAlTYW8gUGF1bG8xEjAQBgNVBAcMCVNhbyBQ
    YXVsbzENMAsGA1UECgwENDJTUDELMAkGA1UECwwCNDIxCzAJBgNVBAMMAjQyMR8w
    HQYJKoZIhvcNAQkBFhBjYWlvQDQyc3Aub3JnLmJyMB4XDTIwMDgwNTAwNTEyOVoX
    DTIxMDgwNTAwNTEyOVowfzELMAkGA1UEBhMCQlIxEjAQBgNVBAgMCVNhbyBQYXVs
    bzESMBAGA1UEBwwJU2FvIFBhdWxvMQ0wCwYDVQQKDAQ0MlNQMQswCQYDVQQLDAI0
    MjELMAkGA1UEAwwCNDIxHzAdBgkqhkiG9w0BCQEWEGNhaW9ANDJzcC5vcmcuYnIw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZpLx6Ka/8CEaM1+pyTe5g
    dVNzBbDymD1DivAk2NQlBu8+rs8w0La1yCupW9RcZbgRyj3G9PH/KUuKVCEJ7I79
    6mjYzDdEU62yu3zrdLkZtBsDq1EcgzUx/0rPgVy5P043yyro1VTp2Hcbg6rw7euE
    1vk5/VRRkuqlB+L3JguRnK5S+d602kVmSBPQNCHb/9sKx0h8pfO9pqfwEppi6iQ6
    PbRofibdbEmlBFqMsE9dzY+8N4yf7P08NdN5ja6SAYEShzJPXFT+o/lhi0C2z29+
    kN/7KHV9icKuPNNhvl8/P47tuWm4xt/X1w9+Ogq6F1DAUS+857IlsLY9nxvla7Cz
    AgMBAAEwDQYJKoZIhvcNAQELBQADggEBAG1PbdsAPtd7t8cCnTsH9bLFy8zAwCr6
    teZBIJOCZhLFoV95g8w+WQVv9Lg0wInn/PD3v8cR7fTcIbb2KBymmiAHp0QlrQag
    bLUtEq7fzdpm3+osPG3fJnki73qVZnfi3xlrfDWggXcOvQ35ApMdKxlca8HkCmWJ
    6xvZeowAhes6qB+V5gwUthlsupeRvhwsFOxbYxBLm3AKV+n+oMHYBzX6XXpQSoRM
    hp6uq//T/YKKXWmjTmDwFjuZoStR5lY0ZiYKtUMIRqUerNGdoAmFV1Tf+g8J+pOH
    C2OvVnK6ZRCl5Xqp9vxi1REILdYPLz/Ap6adSSfzbLjo1eQrBnGW1Z8=
    -----END CERTIFICATE-----
