apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:services
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: influxdb
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8086
    targetPort: http
  selector:
    app: influxdb
  type: ClusterIP
