apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:services
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 5050
---          
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
  - name: http
    protocol: TCP
    port: 5050
    targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer
