apiVersion: v1
kind: ConfigMap
metadata:
  name: ftp-config
data:
  vsftpd.conf: |
    ftpd_banner=Welcome to Caio FTP server.
    anonymous_enable=YES
    local_enable=YES
    write_enable=YES
    local_umask=022
    dirmessage_enable=YES
    xferlog_enable=YES
    xferlog_std_format=YES
    chroot_local_user=YES
    allow_writeable_chroot=YES
    connect_from_port_20=YES
    pam_service_name=vsftpd
    seccomp_sandbox=NO
    ssl_enable=YES
    allow_anon_ssl=NO
    force_local_data_ssl=NO
    force_local_logins_ssl=NO
    require_ssl_reuse=YES
    ssl_ciphers=HIGH
    pasv_enable=YES
    pasv_promiscuous=YES
    pasv_address=172.17.0.10
    pasv_min_port=10000
    pasv_max_port=10000
    rsa_cert_file=/etc/ssl/server.crt
    rsa_private_key_file=/etc/ssl/server.key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      name: ftp
      labels:
        app: ftp
    spec:
      containers:
      - name: ftp
        image: ftp:services
        imagePullPolicy: Never
        ports:
        - name: ftp-data
          containerPort: 20
        - name: ftp-connection
          containerPort: 21
        - name: passv-mode
          containerPort: 10000
        volumeMounts:
        - name: ftp-config
          mountPath: /etc/vsftpd/
      volumes:
        - name: ftp-config
          configMap:
            name: ftp-config
---
apiVersion: v1
kind: Service
metadata:
  name: ftp
spec:
  ports:
  - name: ftp-data
    port: 20
    targetPort: 20
  - name: ftp-connection
    port: 21
    targetPort: 21
  - name: passv-mode
    port: 10000
    targetPort: 10000 
  selector:
    app: ftp
  type: LoadBalancer
